pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                echo '🔄 Checking out code from GitHub...'
                git branch: 'main', 
                    url: 'https://github.com/kshama266/technova-cicd-pipeline.git'
            }
        }
        
        stage('Build') {
            steps {
                echo '🔨 Building Node.js application...'
                bat 'cd src\\app && npm install'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                echo '🐳 Building Docker image...'
                bat 'docker build -t technova-app:%BUILD_NUMBER% .'
            }
        }
        
        stage('Deploy') {
            steps {
                echo '🚀 Deployment ready'
                bat 'echo Build: %BUILD_NUMBER%'
            }
        }
    }
    
    post {
        always {
            echo '🧹 Cleaning up...'
            bat 'docker system prune -f || exit /b 0'
        }
        success {
            echo '✅ SUCCESS!'
        }
        failure {
            echo '❌ FAILED!'
        }
    }
}